### ISSUE TITLE
Empty tables <tr> at the bottom

### ISSUE THREAD

**Issue by equinusocio** [vuese/vuese#20]
Hi, the generated tables have an empty `<tr>` at the bottom.

<img width="691" alt="screenshot 2019-01-08 at 14 56 13" src="https://user-images.githubusercontent.com/10454741/50834969-b4530b80-1355-11e9-8fa2-01e7ac6c60d7.png">

**Comment by HcySunYang** [comment]
https://github.com/vuese/vuese/issues/20
