### ISSUE TITLE
Windows下面运行gen直接NPM报错退出

### ISSUE THREAD

**Issue by a526672351** [vuese/vuese#22]
![image](https://user-images.githubusercontent.com/5345266/50873862-bf14ab80-13fc-11e9-8bdb-dd3812213123.png)

0 info it worked if it ends with ok
1 verbose cli [ 'd:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'd:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'gen' ]
2 info using npm@5.6.0
3 info using node@v8.11.3
4 verbose run-script [ 'pregen', 'gen', 'postgen' ]

13 verbose stack Error: egg-vue-boilerplate@1.0.0 gen: `vuese gen --include="app/web/**/*.vue"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\H004335.WTOIP\AppData\Roaming\nvm\v8.11.3\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\H004335.WTOIP\AppData\Roaming\nvm\v8.11.3\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

**Comment by HcySunYang** [comment]
Reinstall v1.4.5

**Comment by a526672351** [comment]
@HcySunYang 文件遍历生成文档不全，只能便利获取第一个文件夹.vue文件
![image](https://user-images.githubusercontent.com/5345266/50880027-fa70a380-1417-11e9-893b-e0d1a72fdd70.png)
![image](https://user-images.githubusercontent.com/5345266/50880176-70750a80-1418-11e9-878a-1fad45eb29db.png)

**Comment by HcySunYang** [comment]
Please show your `vuese.config.js` or `.vueserc` configuration

**Comment by a526672351** [comment]
@HcySunYang .vueserc 如下
`{
  "include": ["**/*.vue"],
  "exclude": ["node_modules/**/*.vue"],
  "title": "egg-vue"
}`

**Comment by HcySunYang** [comment]
检查你上面的两张截图，你会发现 `layout/index/content/content.vue` 组件已经生成了 `VContent.md`。之所以 `footer.vue` 和 `header.vue` 没有生成对应的 `md` 文档，是因为这两个组件中没有插槽、事件、prop 以及需要暴露的方法，这时候 `vuese` 不会为它生成文档，是为了避免生成空的 `md` 文件。请查看这个 issue: https://github.com/vuese/vuese/issues/18

**Comment by a526672351** [comment]
@HcySunYang https://github.com/a526672351/egg-vue-boilerplate可以查看这个工程结构，加入配置只能生成第一个目录的bug，工程page和里面component目录header.vue里面带有方法的，也有data，都无法生成

**Comment by HcySunYang** [comment]
首先生成文档时只关注一个组件的四个部分：slot、event、props 以及带有 `@vuese` 注解的 method，所以并不会理会 `data`。以你的 header.vue 为例，如果你想要 `menuBtn` 方法包含在生成的文档中，你需要添加 `@vuese` 注解，如下：
```js
export default {
  components: {},
  data() {
    return {
      collapsed: false
    };
  },
  computed: {},
  methods: {
    // @vuese
    menuBtn() {
      this.collapsed = !this.collapsed;
    }
  },
  mounted() {}
};
```
为什么这么设计，文档中有说，请仔细阅读文档：https://github.com/vuese/vuese#write-a-document-for-your-component

**Comment by a526672351** [comment]
@HcySunYang 好的，明白了，还有几个体验不太好的问题如下：
1.组件命名有可能重名区分困难
2.如果props 的类型是Function或Object显示内容换行条例不清晰如下。
![image](https://user-images.githubusercontent.com/5345266/50885003-745c5900-1427-11e9-89ef-a794716d8ae2.png)

**Comment by a526672351** [comment]
3.出现了文档显示错乱的问题。
![image](https://user-images.githubusercontent.com/5345266/50885078-ac639c00-1427-11e9-91ef-41cf84bd01c9.png)
可以下载该仓库组件本地生成复原错乱问题，地址如下：
https://github.com/weifeiyue/vue-datepicker-local/tree/master/src

**Comment by HcySunYang** [comment]
这个问题需要优化，一个临时解决方案是：先在default选项上添加一个注释，用来代替原始默认值即可

**Comment by a526672351** [comment]
等待优化版本
