### ISSUE TITLE
Feature: need Playground

### ISSUE THREAD

**Issue by PanJiaChen** [vuese/vuese#24]
This project is great 👍 .

The vue ecosystem lacks good documentation tools like `docz` or `react-styleguidist`.

But I think the documentation tool must have a Playground to know what the component is doing.

Like this:

![image](https://user-images.githubusercontent.com/8121621/50941746-11b79b80-14c1-11e9-8306-4c9a46a80260.png)

**Comment by HcySunYang** [comment]
Yes, I will post the roadmap as soon as possible, the problems you describe are all planned, and I already have a better idea.

**Comment by davidmoshal** [comment]
why not use [vue-book](https://github.com/asvae/vue-book), it's really great.

**Comment by davidmoshal** [comment]
Btw, MDX apparently works with Vue:
https://github.com/mdx-js/mdx/issues/238

**Comment by HcySunYang** [comment]
I have already released the roadmap, so I will close this issue. If there are good suggestions, I hope to discuss it here: 
https://github.com/vuese/roadmap
thanks.

**Comment by davidmoshal** [comment]
ok, thanks.
