### ISSUE TITLE
希望支持添加组件描述

### ISSUE THREAD

**Issue by Jam1zhu** [vuese/vuese#26]
组件比较多，组内成员英语也参差不齐，希望能支持添加组件描述信息，比如：

![image](https://user-images.githubusercontent.com/21252750/51027162-24b69280-15cb-11e9-9772-f66c805686e5.png)
或者自定义菜单名称

**Comment by Jam1zhu** [comment]
@HcySunYang When will it be updated?

**Comment by HcySunYang** [comment]
these few days...BTW: I work for free, please be patient

**Comment by Jam1zhu** [comment]
无意冒犯，我的英语表达不太好。哈哈，很感谢你们的付出。
