### ISSUE TITLE
Config has no effect on generate

### ISSUE THREAD

**Issue by janiskelemen** [vuese/vuese#28]
Hi,

nice tool! However, I cannot seem to get the config file to work. No matter what I type in there as include value it always loads all .vue files from my project root. Even if I directly enter an include option like **vuese gen --include="assets/js/components/**/*.vue"** it just seems to ignore the given path.

Best regards
Janis

**Comment by HcySunYang** [comment]
Can you provide the approximate structure of your project?

**Comment by janiskelemen** [comment]
it is the default laravel structure. the Vue files life in assets/js/components/**
some example paths:
resources/assets/js/components/table/autocomplete.vue
resources/assets/js/components/dropdown/dropdown.vue
resources/assets/js/components/base/modal-dialog.vue

**Comment by janiskelemen** [comment]
also the --outDir="test" does not change the output folder. It always goes to website folder.

**Comment by HcySunYang** [comment]
The pattern string `"assets/js/components/**/*.vue"` is matching all, do you need `"assets/js/components/*/*.vue"`?

**Comment by HcySunYang** [comment]
@janiskelemen I have released version 1.4.7 to solve this problem.

**Comment by janiskelemen** [comment]
Thanks that worked.
