### ISSUE TITLE
out of memory ?

### ISSUE THREAD

**Issue by ly525** [vuese/vuese#30]
**Describe the bug**
```bash
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```

**To Reproduce**
1. I tried to generate docs for [matsp/material-components-vue](https://github.com/matsp/material-components-vue)
2. clone `matsp/material-components-vue` to my mac, and copy [.vueserc](https://github.com/vuese/vuese/blob/master/.vueserc) of  `vuese/vuese` to the root path of `material-components-vue` (local)
3. run `vuese gen`
4. then I got the following error:
```bash
$ vuese gen
? Select the target to generate Docute - The fastest way to create a documentation site for your pro
ject.
⏳  Start creating markdown files...


<--- Last few GCs --->

[19169:0x103800000]   147834 ms: Mark-sweep 1371.7 (1439.5) -> 1358.5 (1440.0) MB, 258.8 / 0.1 ms  (average mu = 0.276, current mu = 0.226) allocation failure scavenge might not succeed
[19169:0x103800000]   148171 ms: Mark-sweep 1372.5 (1440.0) -> 1360.8 (1440.5) MB, 272.6 / 0.1 ms  (average mu = 0.238, current mu = 0.193) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x31a2df35be3d]
    1: StubFrame [pc: 0x31a2df35d1ff]
Security context: 0x267146d1e6e1 <JSObject>
    2: normalizeString(aka normalizeString) [0x26715e882201] [path.js:~57] [pc=0x31a2df80a7df](this=0x26710d3826f1 <undefined>,path=0x2671aa264761 <String[221]: /Users/somebody/Downloads/material-components-vue-master/node_modules/@vue/babel-preset-app/node_modules/@babel/preset-env/node_modules/@babel/plugin-transform-duplica...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x10003ae75 node::Abort() [/Users/somebody/.nvm/versions/node/v10.14.0/bin/node]
 2: 0x10003b07f node::OnFatalError(char const*, char const*) [/Users/somebody/.nvm/versions/node/v10.14.0/bin/node]
 3: 0x1001a7ad5 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/somebody/.nvm/versions/node/v10.14.0/bin/node]
 4: 0x100572ee2 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/somebody/.nvm/versions/node/v10.14.0/bin/node]
```

**Screenshots**
![image](https://user-images.githubusercontent.com/12668546/51083423-07adcb00-1755-11e9-8570-394e9be98d29.png)

**Which version do you use:**
1. vuese: 1.4.7
2. matsp/material-components-vue: 0.26.1
3. node: v10.14.0
4. MacBook Pro 15 (the year 2015)

**Additional information**
be willing to provide more info if you need.

**Comment by HcySunYang** [comment]
I tried it according to your steps, but it worked fine.
Sorry, based on your information, I can't guess what is going wrong. Can you do more? For example, change a computer or the like. I will release 2.0 in the next few days, maybe you can try it.

**Comment by ly525** [comment]
OK，I will retry later。Thanks for your great work that saving my weekend。best regards 😄

**Comment by ly525** [comment]
I reinstall matsp/material-components-vue, that works fine.

**Comment by HcySunYang** [comment]
Congratulations 😄
